services:
  one-login-simulator:
    image: ghcr.io/govuk-one-login/simulator:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PUBLIC_KEY: "${PUBLIC_KEY_PEM}"
      PUBLIC_KEY_SOURCE: STATIC
      TOKEN_AUTH_METHOD: private_key_jwt
      REDIRECT_URLS: "http://localhost:8080/api/auth/callback/gov-uk-one-login"
      SCOPES: "openid,email"
      PKCE_ENABLED: "true"
      IDENTITY_VERIFICATION_SUPPORTED: "false"
      SIMULATOR_URL: "http://localhost:3000"
      ID_TOKEN_SIGNING_ALGORITHM: RS256
    restart: unless-stopped
